
package org.newpaq;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LWIntegrationService", targetNamespace = "urn:Brierley.LoyaltyWare.LWIntegrationSvc", wsdlLocation = "file:/home/adrian/Arvato/JAXB-Mock/wsdl/LWIntgrService.wsdl")
public class LWIntegrationService
    extends Service
{

    private final static URL LWINTEGRATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException LWINTEGRATIONSERVICE_EXCEPTION;
    private final static QName LWINTEGRATIONSERVICE_QNAME = new QName("urn:Brierley.LoyaltyWare.LWIntegrationSvc", "LWIntegrationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/adrian/Arvato/JAXB-Mock/wsdl/LWIntgrService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LWINTEGRATIONSERVICE_WSDL_LOCATION = url;
        LWINTEGRATIONSERVICE_EXCEPTION = e;
    }

    public LWIntegrationService() {
        super(__getWsdlLocation(), LWINTEGRATIONSERVICE_QNAME);
    }

    public LWIntegrationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LWINTEGRATIONSERVICE_QNAME, features);
    }

    public LWIntegrationService(URL wsdlLocation) {
        super(wsdlLocation, LWINTEGRATIONSERVICE_QNAME);
    }

    public LWIntegrationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LWINTEGRATIONSERVICE_QNAME, features);
    }

    public LWIntegrationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LWIntegrationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ILWIntegrationService
     */
    @WebEndpoint(name = "BasicHttpBinding_ILWIntegrationService")
    public ILWIntegrationService getBasicHttpBindingILWIntegrationService() {
        return super.getPort(new QName("urn:Brierley.LoyaltyWare.LWIntegrationSvc", "BasicHttpBinding_ILWIntegrationService"), ILWIntegrationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ILWIntegrationService
     */
    @WebEndpoint(name = "BasicHttpBinding_ILWIntegrationService")
    public ILWIntegrationService getBasicHttpBindingILWIntegrationService(WebServiceFeature... features) {
        return super.getPort(new QName("urn:Brierley.LoyaltyWare.LWIntegrationSvc", "BasicHttpBinding_ILWIntegrationService"), ILWIntegrationService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LWINTEGRATIONSERVICE_EXCEPTION!= null) {
            throw LWINTEGRATIONSERVICE_EXCEPTION;
        }
        return LWINTEGRATIONSERVICE_WSDL_LOCATION;
    }

}
